Repository numbble/frontend, pull requests merged in 2022-05, with the labels that each got.

#8 🐛 ChatRoom Page 스타일 에러 수정
  src/components/Chat/MessageBox/MessageBox.tsx
  src/components/Chat/MessageItem/styles.ts
  src/components/Common/PageHeader/PageHeader.tsx
  src/components/Common/PageHeader/styles.ts
  src/pages/ChatRoomPage/ChatRoomPage.tsx
Labels: bug

#11 ProfilePage 수정사항 업데이트
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
  src/components/Profile/ProfileNavigation/styles.ts
  src/components/Profile/VideoItem/VideoItem.tsx
  src/data/index.ts
  src/data/profileData.ts
  src/data/videoData.ts
Labels: enhancement

#12 ✨ VideoUploadPage UI 및 기본기능 구현
  src/App.tsx
  src/pages/UploadPage.tsx
  src/pages/VideoUploadPage/VideoUploadPage.tsx
  src/pages/VideoUploadPage/styles.ts
  src/pages/index.ts
Labels: enhancement

#13 ✨ mock server 이용해서 data fetching 로직 추가 (chatList)
  package-lock.json
  package.json
  src/components/Chat/ChatItem/ChatItem.tsx
  src/pages/ChatListPage/ChatListPage.tsx
  src/utils/api.ts
  src/utils/swr.ts
Labels: enhancement

#14 ♻ Chat Page의 기존 데이터를 Mock 서버 데이터로 교체
  src/components/Chat/ChatItem/ChatItem.tsx
  src/components/ChatList/ChatItem/ChatItem.tsx
  src/components/ChatList/ChatItem/styles.ts
  src/components/ChatList/ChatList/ChatList.tsx
  src/components/ChatList/ChatList/styles.ts
  src/components/ChatList/EmptyChat/EmptyChat.tsx
  src/components/ChatList/EmptyChat/styles.ts
  src/components/ChatRoom/MessageBox/MessageBox.tsx
  src/components/ChatRoom/MessageBox/styles.ts
  src/components/ChatRoom/MessageItem/MessageItem.tsx
  src/components/ChatRoom/MessageItem/styles.ts
  src/components/ChatRoom/MessageList/MessageList.tsx
  src/components/ChatRoom/MessageList/styles.ts
  src/components/Common/Loading/Loading.tsx
  src/components/Common/Loading/styles.ts
  src/components/index.ts
  src/data/chatData.ts
  src/data/index.ts
  src/data/types.d.ts
  src/pages/ChatListPage/ChatListPage.tsx
  src/pages/ChatRoomPage/ChatRoomPage.tsx
  src/utils/dateConverter.ts
Labels: enhancement

#16 ✨ MainPage UI 및 영상 정지 및 재생 기능 구현
  package-lock.json
  package.json
  src/components/Main/DescriptionBox/DescriptionBox.tsx
  src/components/Main/DescriptionBox/styles.ts
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/MainHeader/styles.ts
  src/components/Main/PlayerMenu/PlayerMenu.tsx
  src/components/Main/PlayerMenu/styles.ts
  src/components/Main/VideoPlayer/VideoPlayer.tsx
  src/components/Main/VideoPlayer/styles.ts
  src/components/index.ts
  src/pages/MainPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/styles.ts
  src/pages/index.ts
Labels: enhancement

#19 🤡 영상 mock data 추가 및 기존 데이터 useSWR 이용해서 대체
  server/db.json
  server/routes.json
  src/components/Common/VideoItem/VideoItem.tsx
  src/components/Common/VideoItem/styles.ts
  src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
  src/components/index.ts
  src/data/types.d.ts
  src/utils/api.ts
Labels: enhancement

#20 ✨ videoItem 클릭시 재생화면으로 이동하도록 페이지 라우팅 및 관련 컴포넌트 동적으로 수정
  server/db.json
  src/App.tsx
  src/components/Common/VideoItem/VideoItem.tsx
  src/components/Main/DescriptionBox/DescriptionBox.tsx
  src/components/Main/PlayerMenu/PlayerMenu.tsx
  src/components/Main/VideoPlayer/VideoPlayer.tsx
  src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
  src/data/types.d.ts
  src/pages/MainPage/MainPage.tsx
  src/utils/api.ts
Labels: enhancement

#21 💄 UploadPage UI 전면 수정
  src/pages/VideoUploadPage/VideoUploadPage.tsx
  src/pages/VideoUploadPage/styles.ts
Labels: enhancement

#22 🚀 Heroku 환경에 맞춰 json-server 수정 후 배포
  package.json
  server/index.js
  server/routes.json
Labels: refactor ♻

#24 ✨ AdminPage 라우팅 설정 및 AdminNav 추가
  src/App.tsx
  src/components/Admin/AdminContents/AdminContents.tsx
  src/components/Admin/AdminContents/styles.ts
  src/components/Admin/AdminNav/AdminNav.tsx
  src/components/Admin/AdminNav/styles.ts
  src/components/Admin/AdminUser/AdminUser.tsx
  src/components/index.ts
  src/pages/AdminPage/AdminPage.tsx
  src/pages/AdminPage/styles.ts
  src/pages/index.ts
Labels: enhancement

#28 ✨ Search Result Page 구현
  src/App.tsx
  src/components/AppLayout/styles.ts
  src/components/Common/PageHeader/styles.ts
  src/components/Common/VideoList/VideoList.tsx
  src/components/Common/VideoList/styles.ts
  src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
  src/components/Profile/ProfileNavigation/styles.ts
  src/components/Search/HistoryList/HistoryList.tsx
  src/components/Search/HistoryList/styles.ts
  src/components/Search/SearchBar/SearchBar.tsx
  src/components/index.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/types.d.ts
  src/pages/SearchResultPage/SearchResultPage.tsx
  src/pages/SearchResultPage/styles.ts
  src/pages/index.ts
Labels: enhancement

#35 💄 AppLayout의 navbar 아이콘 적용 및 스타일 수정
  src/App.tsx
  src/assets/img/kakaoLogin.png
  src/assets/svg/chat_nav.svg
  src/assets/svg/home.svg
  src/assets/svg/profile.svg
  src/assets/svg/searchbar.svg
  src/assets/svg/upload.svg
  src/components/Layouts/AppLayout/AppLayout.tsx
  src/components/Layouts/AppLayout/styles.ts
  src/components/Login/KakaoLogin/Auth.tsx
  src/components/Login/KakaoLogin/KakaoLogin.tsx
  src/components/Login/KakaoLogin/KakaoRedirectHandler.tsx
  src/components/Login/KakaoLogin/styles.ts
  src/components/index.ts
  src/types/images.d.ts
  tsconfig.json
Labels: enhancement

#38 ✨ MainPage 아이콘 변경 및 숨기기 버튼 추가
  src/assets/svg/chat.svg
  src/assets/svg/follow.svg
  src/assets/svg/more.svg
  src/assets/svg/save.svg
  src/assets/svg/unSave.svg
  src/components/Main/DescriptionBox/DescriptionBox.tsx
  src/components/Main/DescriptionBox/styles.ts
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/MainHeader/styles.ts
  src/components/Main/PlayerMenu/PlayerMenu.tsx
  src/components/Main/PlayerMenu/styles.ts
  src/components/Main/VideoPlayer/VideoPlayer.tsx
  src/pages/MainPage/MainPage.tsx
Labels: enhancement

#41 ♻️ VideoItem 로직 수정 및 video type 변경
  src/components/Admin/ContentsEdit/ContentsEdit.tsx
  src/components/Admin/VideoDataTable/VideoDataTable.tsx
  src/components/Common/VideoItem/VideoItem.tsx
  src/components/Common/VideoItem/styles.ts
  src/components/Common/VideoList/VideoList.tsx
  src/components/Common/VideoList/styles.ts
  src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
  src/components/Search/HorizonVideoList/HorizonVideoList.tsx
  src/components/Search/HorizonVideoList/styles.ts
  src/components/index.ts
  src/data/types.d.ts
  src/pages/AdminContentPage/AdminContentPage.tsx
  src/pages/AdminDashBoard/AdminDashBoard.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchResultPage/SearchResultPage.tsx
Labels: enhancement

#42 ♻️ 카카오 소셜 로그인 로직 리팩토링
  .gitignore
  src/components/Login/KakaoLogin/KakaoLogin.tsx
  src/components/Login/KakaoLogin/KakaoRedirectHandler.tsx
  src/utils/api.ts
  src/utils/swr.ts
Labels: enhancement

#44 ✨ UploadPage UI 수정 및 multi-form 적용
  src/App.tsx
  src/assets/svg/thumbnail.svg
  src/assets/svg/video.svg
  src/components/Common/PageHeader/styles.ts
  src/components/Upload/FileInput/ImageInput.tsx
  src/components/Upload/FileInput/VideoInput.tsx
  src/components/Upload/FileInput/styles.ts
  src/components/Upload/Input/Category.tsx
  src/components/Upload/Input/Condition.tsx
  src/components/Upload/Input/styles.ts
  src/components/Upload/InputBox/InputBox.tsx
  src/components/Upload/InputBox/styles.ts
  src/components/index.ts
  src/pages/VideoUploadPage/VideoUploadPage.tsx
  src/pages/VideoUploadPage/styles.ts
  src/styles/GlobalStyle.ts
  src/utils/api.ts
  tsconfig.json
Labels: enhancement

#45 ✨ 영상 삭제 구현 (모달창, 영상재생 컴포넌트 재사용)
  src/components/Common/Modal/DeleteModal.tsx
  src/components/Common/Modal/LoginModal.tsx
  src/components/Common/Modal/styles.ts
  src/components/Main/ContentsWrap/ContentsWrap.tsx
  src/components/Main/DescriptionBox/styles.ts
  src/components/Main/NavMenu/ControlMenu.tsx
  src/components/Main/NavMenu/PlayerMenu.tsx
  src/components/Main/NavMenu/styles.ts
  src/components/index.ts
  src/utils/api.ts
Labels: enhancement

#49 ✨ 영상 업로드 로직 구현 / 메세지 모달창 추가
  src/components/Common/Modal/DeleteModal.tsx
  src/components/Common/Modal/LoginModal.tsx
  src/components/Common/Modal/MessageModal.tsx
  src/components/Common/Modal/styles.ts
  src/components/index.ts
  src/pages/VideoUploadPage/VideoUploadPage.tsx
  src/utils/api.ts
Labels: enhancement

#50 ✨ 영상 삭제 구현, 영상 재생 api 교체
  src/components/Common/Modal/DeleteModal.tsx
  src/components/Main/ContentsWrap/ContentsWrap.tsx
  src/components/Main/DescriptionBox/DescriptionBox.tsx
  src/data/types.d.ts
  src/pages/MainPage/MainPage.tsx
  src/utils/api.ts
Labels: enhancement

#51 ✨ 영상재생 페이지에 좋아요 등록 구현
  src/components/Main/ContentsWrap/ContentsWrap.tsx
  src/components/Main/NavMenu/PlayerMenu.tsx
  src/components/Main/NavMenu/styles.ts
  src/pages/MainPage/MainPage.tsx
  src/utils/api.ts
  src/utils/swr.ts
Labels: enhancement

#54 Feature/profile
  src/App.tsx
  src/components/Layouts/AppLayout/AppLayout.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/utils/api.ts
Labels: enhancement

#60 :bug: 카카오 소셜 로그인 redirect uri 수정
  src/utils/api.ts
Labels: bug 🐛

#64 ♻️ Private Route 설정, 로그인 여부에 따라 LoginModal 보여주기 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/Common/Modal/LoginModal.tsx
  src/components/Layouts/AppLayout/AppLayout.tsx
  src/components/Login/KakaoLogin/KakaoRedirectHandler.tsx
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/MainHeader/styles.ts
  src/components/Main/NavMenu/IconFeature/ChatButton.tsx
  src/components/Main/NavMenu/IconFeature/LikeButton.tsx
  src/components/Main/NavMenu/IconFeature/ProfileFollow.tsx
  src/components/Main/NavMenu/UserVideoNav/UserVideoNav.tsx
  src/components/Route/PrivateRoute.tsx
  src/components/index.ts
  src/index.tsx
  src/pages/ChatListPage/ChatListPage.tsx
  src/pages/NotificationPage/NotificationPage.tsx
  src/pages/index.ts
  src/recoil/atom.ts
  src/utils/isLogin.ts
Labels: refactor ♻

#75 ♻ 프로필 페이지 & 팔로우 페이지
  src/components/Common/ProfileInputs/styles.ts
  src/components/Main/NavMenu/IconFeature/ProfileFollow.tsx
  src/components/Profile/FollowButton/FollowButton.tsx
  src/components/Profile/FollowButton/styles.ts
  src/components/Profile/ProfileHeader/styles.ts
  src/components/Profile/ProfileNavigation/styles.ts
  src/hooks/useFollow.ts
  src/pages/FollowPage/FollowPage.tsx
  src/pages/OnBoard/NewProfilePage/styles.ts
  src/pages/Profile/FollowPage/FollowPage.tsx
  src/pages/Profile/FollowPage/styles.ts
  src/pages/Profile/ProfileEditPage/ProfileEditPage.tsx
  src/pages/Profile/ProfileEditPage/styles.ts
  src/pages/Profile/ProfilePage/ProfilePage.tsx
  src/pages/Profile/ProfilePage/styles.ts
  src/pages/index.ts
Labels: refactor ♻
